export {default as Homepage} from './Homepage/Homepage'
export {default as Contact} from './Contact/Contact'
export {default as Login} from './Login/Login'
export {default as Places} from './Places/Places'
export {default as Signup} from './Signup/Signup'